# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LicAreaScraper
                                 A QGIS plugin
 Plugin for getting licence area SHP-file 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-07
        copyright            : (C) 2021 by Michael Chernov
        email                : mihail.tchernov@yandex.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LicAreaScraper class from file LicAreaScraper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lic_area_scraper import LicAreaScraper
    return LicAreaScraper(iface)
